package org.example.model;

import lombok.Data;

@Data
public class Memo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memos.id
     *
     * @mbg.generated Sat Mar 04 17:45:25 JST 2023
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memos.title
     *
     * @mbg.generated Sat Mar 04 17:45:25 JST 2023
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column memos.body
     *
     * @mbg.generated Sat Mar 04 17:45:25 JST 2023
     */
    private String body;

    private String user;
}